print("sreenu")
print("welcome to world of programming")
print("Let's begin!!!")
print("hello hi")
print("github to work with the others codes and projects")
print("connectivity")
print("connection with the users")
print("working on different different modules")
print("working on different different modules")
print("Bye")